// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Slp.Common.DataAccess;

namespace Slp.Migrations.POSTGRESQL.Slp.Migrations.POSTGRESQL
{
    [DbContext(typeof(SlpDbContext))]
    partial class SlpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Slp.Common.Models.DbModels.DatabaseState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("BlockTip")
                        .HasColumnType("integer");

                    b.Property<string>("BlockTipHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastStatusUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("SlpDatabaseState");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpAddress", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("BlockHeight")
                        .HasMaxLength(128)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("BlockHeight");

                    b.ToTable("SlpAddress");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpBlock", b =>
                {
                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BlockTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("Hash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<bool>("IsSlp")
                        .HasColumnType("boolean");

                    b.HasKey("Height");

                    b.HasIndex("Hash");

                    b.ToTable("SlpBlock");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpToken", b =>
                {
                    b.Property<byte[]>("Hash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("ActiveMint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("BlockHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("BlockLastActiveMint")
                        .HasColumnType("integer");

                    b.Property<int?>("BlockLastActiveSend")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CirculatingSupply")
                        .HasColumnType("numeric(38,0)");

                    b.Property<int>("Decimals")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentSha256Hex")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DocumentUri")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("LastActiveSend")
                        .HasColumnType("integer");

                    b.Property<string>("MintingBatonStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("SatoshisLockedUp")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("TotalBurned")
                        .HasColumnType("numeric(38,0)");

                    b.Property<decimal?>("TotalMinted")
                        .HasColumnType("numeric(38,0)");

                    b.Property<int?>("TxnsSinceGenesis")
                        .HasColumnType("integer");

                    b.Property<int?>("ValidAddresses")
                        .HasColumnType("integer");

                    b.Property<int?>("ValidTokenUtxos")
                        .HasColumnType("integer");

                    b.Property<int>("VersionType")
                        .HasColumnType("integer");

                    b.HasKey("Hash");

                    b.HasIndex("BlockHeight");

                    b.ToTable("SlpToken");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpTransaction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("AdditionalTokenQuantity")
                        .HasColumnType("numeric(38,0)");

                    b.Property<int?>("BlockHeight")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Hash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("InvalidReason")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("MintBatonVOut")
                        .HasColumnType("integer");

                    b.Property<byte[]>("SlpTokenId")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<int>("SlpTokenType")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TokenInputSum")
                        .HasColumnType("numeric(38,0)");

                    b.Property<decimal?>("TokenOutputSum")
                        .HasColumnType("numeric(38,0)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlockHeight");

                    b.HasIndex("Hash");

                    b.HasIndex("SlpTokenId");

                    b.ToTable("SlpTransaction");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpTransactionInput", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BlockchainSatoshis")
                        .HasColumnType("numeric(38,0)");

                    b.Property<decimal>("SlpAmount")
                        .HasColumnType("numeric(38,0)");

                    b.Property<long>("SlpTransactionId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("SourceTxHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<int>("VOut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("SlpTransactionId");

                    b.ToTable("SlpTransactionInput");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpTransactionOutput", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AddressId")
                        .HasMaxLength(128)
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(38,0)");

                    b.Property<decimal>("BlockchainSatoshis")
                        .HasColumnType("numeric(38,0)");

                    b.Property<long?>("NextInputId")
                        .HasColumnType("bigint");

                    b.Property<long>("SlpTransactionId")
                        .HasColumnType("bigint");

                    b.Property<int>("VOut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NextInputId");

                    b.HasIndex("SlpTransactionId");

                    b.ToTable("SlpTransactionOutput");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpAddress", b =>
                {
                    b.HasOne("Slp.Common.Models.DbModels.SlpBlock", "Block")
                        .WithMany()
                        .HasForeignKey("BlockHeight");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpToken", b =>
                {
                    b.HasOne("Slp.Common.Models.DbModels.SlpBlock", "Block")
                        .WithMany()
                        .HasForeignKey("BlockHeight");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpTransaction", b =>
                {
                    b.HasOne("Slp.Common.Models.DbModels.SlpBlock", "Block")
                        .WithMany()
                        .HasForeignKey("BlockHeight");

                    b.HasOne("Slp.Common.Models.DbModels.SlpToken", "SlpToken")
                        .WithMany("Transactions")
                        .HasForeignKey("SlpTokenId");

                    b.Navigation("Block");

                    b.Navigation("SlpToken");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpTransactionInput", b =>
                {
                    b.HasOne("Slp.Common.Models.DbModels.SlpAddress", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Slp.Common.Models.DbModels.SlpTransaction", "SlpTransaction")
                        .WithMany("SlpTransactionInputs")
                        .HasForeignKey("SlpTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("SlpTransaction");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpTransactionOutput", b =>
                {
                    b.HasOne("Slp.Common.Models.DbModels.SlpAddress", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slp.Common.Models.DbModels.SlpTransactionInput", "NextInput")
                        .WithMany()
                        .HasForeignKey("NextInputId");

                    b.HasOne("Slp.Common.Models.DbModels.SlpTransaction", "SlpTransaction")
                        .WithMany("SlpTransactionOutputs")
                        .HasForeignKey("SlpTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("NextInput");

                    b.Navigation("SlpTransaction");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpToken", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Slp.Common.Models.DbModels.SlpTransaction", b =>
                {
                    b.Navigation("SlpTransactionInputs");

                    b.Navigation("SlpTransactionOutputs");
                });
#pragma warning restore 612, 618
        }
    }
}
